In [ ]:
import tensorflow as tf
import numpy as np
import requests
import io

In [ ]:
cifar_label_name=['apple', 'beaver', 'bottle', 'butterfly', 'castle',
'clock', 'couch', 'leopard', 'rose', 'shark']

# requests 라이브러리를 이용해 데이터 다운로드
data_url = 'https://codepresso-online-platform-public.s3.ap-northeast-2.amazonaws.com/learning-resourse/Tensorflow+2.0+%EB%94%A5%EB%9F%AC%EB%8B%9D+%EC%99%84%EB%B2%BD+%EA%B0%80%EC%9D%B4%EB%93%9C/cifar-10-codepresso.npz'
response = requests.get(data_url)
response.raise_for_status()

# 다운로드 받은 데이터를 읽어 들여 Input tensor 와 Target tensor 준비
with np.load(io.BytesIO(response.content)) as cifar_10_codepresso_data:
  # 학습 이미지 데이터(np.ndarry, shape=(5000, 32, 32, 3))
  train_images = cifar_10_codepresso_data['train_images']
  # 학습 라벨 데이터(np.ndarry, shape=(5000, ))
  train_labels = cifar_10_codepresso_data['train_labels']

  # 테스트 이미지 데이터(np.ndarry, shape=(1000, 32, 32, 3))
  test_images = cifar_10_codepresso_data['test_images']
  # 테스트 라벨 데이터(np.ndarry, shape=(1000, ))
  test_labels = cifar_10_codepresso_data['test_labels']

In [ ]:
test_images.shape, test_labels.shape

((1000, 32, 32, 3), (1000,))

In [ ]:
train_images.shape, train_labels.shape

((5000, 32, 32, 3), (5000,))

In [ ]:
train_images = train_images/255.
test_images = test_images/255.

In [ ]:
train_images[:1]

array([[[[0.32941176, 0.32941176, 0.3254902 ],
         [0.33333333, 0.33333333, 0.32156863],
         [0.32941176, 0.30588235, 0.29019608],
         ...,
         [0.38431373, 0.38823529, 0.38431373],
         [0.42352941, 0.42745098, 0.41960784],
         [0.43137255, 0.42352941, 0.4       ]],

        [[0.42745098, 0.42745098, 0.41960784],
         [0.40392157, 0.40392157, 0.39607843],
         [0.38431373, 0.36470588, 0.35294118],
         ...,
         [0.39607843, 0.39607843, 0.4       ],
         [0.42352941, 0.42745098, 0.42352941],
         [0.37254902, 0.36470588, 0.34509804]],

        [[0.50588235, 0.50588235, 0.47058824],
         [0.4627451 , 0.4627451 , 0.48627451],
         [0.43529412, 0.43137255, 0.44313725],
         ...,
         [0.30980392, 0.31372549, 0.30980392],
         [0.39215686, 0.39607843, 0.38431373],
         [0.41176471, 0.40392157, 0.38039216]],

        ...,

        [[0.25882353, 0.25098039, 0.23921569],
         [0.24705882, 0.22745098, 0.20392157]

In [ ]:
from tensorflow.keras.utils import to_categorical

In [ ]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [ ]:
train_labels.shape, test_labels.shape

((5000, 10), (1000, 10))

In [ ]:
from tensorflow.keras import models, layers

In [ ]:
del model

In [ ]:
model = models.Sequential()

In [ ]:
model.add(layers.Conv2D(filters=16, kernel_size=(3,3), activation='relu', input_shape=(32,32,3)))
model.add(layers.MaxPool2D(pool_size=(2,2)))

model.add(layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu'))
model.add(layers.MaxPool2D(pool_size=(2,2)))

model.add(layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu'))

#flatten
model.add(layers.Flatten())
#classification module
model.add(layers.Dense(units=10))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 30, 30, 16)        448       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 15, 15, 16)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 13, 13, 32)        4640      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 6, 6, 32)          0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 4, 4, 64)          18496     
_________________________________________________________________
flatten_2 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)               

In [ ]:
model.compile(loss=tf.keras.losses.CategoricalCrossentropy(from_logits = True), optimizer='rmsprop', metrics=['accuracy'])
#tf.keras.losses.CategoricalCrossentropy(from_logits = True)

In [ ]:
model.fit(x=train_images, y=train_labels, epochs=60, batch_size=64, validation_split=0.2)

Epoch 1/60
63/63 [==============================] - 32s 10ms/step - loss: 1.9263 - accuracy: 0.3113 - val_loss: 1.7962 - val_accuracy: 0.3480
Epoch 2/60
63/63 [==============================] - 0s 5ms/step - loss: 1.6760 - accuracy: 0.4173 - val_loss: 1.7303 - val_accuracy: 0.3930
Epoch 3/60
63/63 [==============================] - 0s 4ms/step - loss: 1.5510 - accuracy: 0.4585 - val_loss: 1.5847 - val_accuracy: 0.4420
Epoch 4/60
63/63 [==============================] - 0s 5ms/step - loss: 1.4488 - accuracy: 0.5050 - val_loss: 1.5874 - val_accuracy: 0.4360
Epoch 5/60
63/63 [==============================] - 0s 4ms/step - loss: 1.3969 - accuracy: 0.5195 - val_loss: 1.5405 - val_accuracy: 0.4610
Epoch 6/60
63/63 [==============================] - 0s 5ms/step - loss: 1.3328 - accuracy: 0.5390 - val_loss: 1.4277 - val_accuracy: 0.5160
Epoch 7/60
63/63 [==============================] - 0s 5ms/step - loss: 1.2714 - accuracy: 0.5652 - val_loss: 1.4353 - val_accuracy: 0.5240
Epoch 8/60
63/63 [

In [ ]:
pred = model.predict(test_images[:2])

In [ ]:
pred_idx = pred.argmax(axis=1)

In [ ]:
pred_idx

array([3, 3])

In [ ]:
test_labels[:2]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
loss, accuracy = model.evaluate(test_images, test_labels)

32/32 [==============================] - 0s 5ms/step - loss: 1.4697 - accuracy: 0.7000
